-- liquibase formatted sql

-- changeset jwozniak:1674499120324-1
CREATE TABLE heatingsystem.iot_user
(
    id            UUID NOT NULL,
    creation_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    email         VARCHAR(255),
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    CONSTRAINT "iot_userPK" PRIMARY KEY (id)
);

-- changeset jwozniak:1674499120324-2
CREATE TABLE heatingsystem.plant
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    update_date     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    familiar_name   VARCHAR(255),
    location        VARCHAR(255),
    max_humidity    numeric(19, 2),
    max_temperature numeric(19, 2),
    min_humidity    numeric(19, 2),
    min_temperature numeric(19, 2),
    sensor_name     VARCHAR(255),
    user_id         UUID,
    CONSTRAINT "plantPK" PRIMARY KEY (id)
);

-- changeset jwozniak:1674499120324-3
ALTER TABLE heatingsystem.plant
    ADD FOREIGN KEY (user_id) REFERENCES heatingsystem.iot_user (id);

