-- liquibase formatted sql

-- changeset jwozniak:1674687559207-1
CREATE TABLE heatingsystem.measurement
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    humidity    INTEGER,
    temperature numeric(19, 2),
    timestamp   TIMESTAMP WITHOUT TIME ZONE,
    plant_id    BIGINT,
    CONSTRAINT "measurementPK" PRIMARY KEY (id)
);

-- changeset jwozniak:1674687559207-2
ALTER TABLE heatingsystem.measurement
    ADD FOREIGN KEY (plant_id) REFERENCES heatingsystem.plant (id);

