server:
  port: 8880
  servlet:
    context-path: /heatingsystem/api

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/heatingsystem
    username: db
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    default-schema: heatingsystem
  security:
    oauth2:
      client:
        registration:
          notification-client:
            provider: keycloak
            client-id: app-backend # nazwa zdefiniowanego w keycloaku klienta
            client-secret: LuPhFzyMlETrg9oYUljsfoX6pHRJqAGo # secret z keycloaka
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://130.61.149.252:8443/auth/realms/app

app:
  keycloak:
    login: keycloak
    password: keycloak
    api-path: http://130.61.149.252:8443/auth/
    redirect-uri: http://130.61.149.252:8443/
    client-id: app-backend
    client-secret: LuPhFzyMlETrg9oYUljsfoX6pHRJqAGo
    realm: app

auth:
  endpoints:
    unsecured: /actuator/**, /v3/api-docs/**, /swagger-ui/**

# SIMULATION CONFIGURATION
simulation:
  logic:
    min:
      temperature:
        during:
          classes: 20
        if:
          unused: 15
      minutes:
        before:
          classes:
            to:
              start:
                heating: 15
  calculation:
    length:
      minutes: 300
  outside:
    temperature: 15
  atmospheric:
    pressure: 98000
  #    currently at every minute
  cron: 0 1/1 * * * ?
